// Auto-generated. Do not edit!

// (in-package lqrrt_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.failure_reason = null;
    }
    else {
      if (initObj.hasOwnProperty('failure_reason')) {
        this.failure_reason = initObj.failure_reason
      }
      else {
        this.failure_reason = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveResult
    // Serialize message field [failure_reason]
    bufferOffset = _serializer.string(obj.failure_reason, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveResult
    let len;
    let data = new MoveResult(null);
    // Deserialize message field [failure_reason]
    data.failure_reason = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.failure_reason.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lqrrt_ros/MoveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2de13b23a1f75564b266f8fcabfafba6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    
    string failure_reason
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveResult(null);
    if (msg.failure_reason !== undefined) {
      resolved.failure_reason = msg.failure_reason;
    }
    else {
      resolved.failure_reason = ''
    }

    return resolved;
    }
};

module.exports = MoveResult;
